const companyFieldNames = {
  legalForm: 'LEGAL_FORM',
  legalFormId: 'LEGAL_FORM',
  taxationSystem: 'TAXATION_SYSTEM',
  inn: 'INN',
  officialName: 'OFFICIAL_NAME',
  unofficialName: 'UNOFFICIAL_NAME',
  directorFullName: 'DIRECTOR_FULL_NAME',
  legalAddress: 'LEGAL_ADDRESS',
  postcode: 'POSTCODE',
  kpp: 'KPP',
  ogrn: 'OGRN',
  oktmo: 'OKTMO',
  bankName: 'BANK_NAME',
  checkingAccount: 'CHECKING_ACCOUNT',
  correspondentAccount: 'CORRESPONDENT_ACCOUNT',
  bic: 'BIC',
  email: 'EMAIL',
  phoneNumber: 'PHONE_NUMBER',
  logo: 'LOGO',
  logoRemoteUrl: 'LOGO',
  companyConfirmationRecords: 'COMPANY_CONFIRMATION_RECORDS',
};

export const getCompanyFieldName = name => companyFieldNames[name];
