export const EXECUTION_STATUS = {
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  CONFIRMED: 'CONFIRMED',
  IN_ASSEMBLY: 'IN_ASSEMBLY',
  IN_TRANSIT: 'IN_TRANSIT',
  DISPUTE_OPENED: 'DISPUTE_OPENED',
  MEDAGREGATOR_INTERVENED: 'MEDAGREGATOR_INTERVENED',
  DELIVERED: 'DELIVERED',
};

export const EXECUTION_STATUS_LABEL = {
  PAYMENT_PENDING: 'не оплачен',
  CONFIRMED: 'подтвержден',
  IN_ASSEMBLY: 'в сборке',
  IN_TRANSIT: 'в пути',
  DISPUTE_OPENED: 'открыт спор',
  MEDAGREGATOR_INTERVENED: 'вмешался medagregator',
  DELIVERED: 'доставлен',
};
