export const initFieldValues = {
  bankName: '',
  bic: '',
  checkingAccount: '',
  correspondentAccount: '',
  companyConfirmationRecords: [],
  directorFullName: '',
  email: '',
  inn: '',
  kpp: '',
  legalAddress: '',
  legalFormId: '',
  logo: null,
  officialName: '',
  ogrn: '',
  oktmo: '',
  phoneNumber: '+7',
  postcode: '',
  taxationSystem: null,
  unofficialName: '',
};
