name: Linters and unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: Install dependencies
      run: yarn

  lintScripts:
    name: Lint scripts
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn

      - run: yarn run ci:lint-js

  lintStyles:
    name: Lint styles
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn

      - run: yarn run ci:lint-css

  lintTypes:
    name: Lint Types
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn

      - run: yarn run types:check

  unitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn

      - run: yarn run ci:jest
