# Workflow name
name: Auto-Run Chromatic

# Event for the workflow
on:
  push:
    branches:
      - 'master'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn

      # 👇 Checks if the branch is main and accepts all changes in Chromatic
      # https://www.chromatic.com/docs/github-actions#github-squashrebase-merge-and-the-main-branch
      - name: Publish to Chromatic and auto accept changes
        uses: chromaui/action@v1
        # Required options for the Chromatic GitHub Action
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true # 👈 Option to accept all changes
